package com.doooly.dao.payment;

import com.doooly.entity.payment.AdPayRecord;
import com.doooly.entity.payment.AdPayRecordExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AdPayRecordDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_record
     *
     * @mbg.generated
     */
    long countByExample(AdPayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_record
     *
     * @mbg.generated
     */
    int deleteByExample(AdPayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_record
     *
     * @mbg.generated
     */
    int insert(AdPayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_record
     *
     * @mbg.generated
     */
    int insertSelective(AdPayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_record
     *
     * @mbg.generated
     */
    List<AdPayRecord> selectByExample(AdPayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_record
     *
     * @mbg.generated
     */
    AdPayRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AdPayRecord record, @Param("example") AdPayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AdPayRecord record, @Param("example") AdPayRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdPayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdPayRecord record);
}