package com.doooly.dao.payment;

import com.doooly.entity.payment.AdPayRefundRecord;
import com.doooly.entity.payment.AdPayRefundRecordExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AdPayRefundRecordDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_refund_record
     *
     * @mbg.generated
     */
    long countByExample(AdPayRefundRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_refund_record
     *
     * @mbg.generated
     */
    int deleteByExample(AdPayRefundRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_refund_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_refund_record
     *
     * @mbg.generated
     */
    int insert(AdPayRefundRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_refund_record
     *
     * @mbg.generated
     */
    int insertSelective(AdPayRefundRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_refund_record
     *
     * @mbg.generated
     */
    List<AdPayRefundRecord> selectByExample(AdPayRefundRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_refund_record
     *
     * @mbg.generated
     */
    AdPayRefundRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_refund_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AdPayRefundRecord record, @Param("example") AdPayRefundRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_refund_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AdPayRefundRecord record, @Param("example") AdPayRefundRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_refund_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdPayRefundRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ad_pay_refund_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdPayRefundRecord record);
}