/**
 * This code generated by CodeGenerator<ptma@163.com>
 */
package com.doooly.dao.reachad;


import com.doooly.entity.reachad.AdReturnPointsLog;

import java.util.List;

/**
 * <p>Mapper接口</p>
 * <p>Table: ad_return_points_log - 返积分日志</p>
 * @since 2018-11-19 11:16:36
 */

public interface AdReturnPointsLogDao {
	/**
	 *保存,未经校验,禁止直接调用
	 */
	void save(AdReturnPointsLog model);
	
	/**
	 *获取单个对象,未经校验,禁止直接调用
	 */
	AdReturnPointsLog getByCondition(AdReturnPointsLog model);
	
	/**
	 *查询多个对象,未经校验,禁止直接调用
	 */
	List<AdReturnPointsLog> getListByCondition(AdReturnPointsLog model);
	
	/**
	 *修改,未经校验,禁止直接调用
	 */
	Integer update(AdReturnPointsLog model);

}