package com.doooly.common.webservice.delegate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "GetVerificationCodeDelegate", targetNamespace = "http://pay.reachlife.com/")
public interface GetVerificationCodeDelegate {

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "_GetVerificationCode")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "_GetVerificationCode", targetNamespace = "http://pay.reachlife.com/", className = "com.reachlife.pay.GetVerificationCode")
	@ResponseWrapper(localName = "_GetVerificationCodeResponse", targetNamespace = "http://pay.reachlife.com/", className = "com.reachlife.pay.GetVerificationCodeResponse")
	public String getVerificationCode(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") int arg3);

}
