package com.doooly.entity.payment;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

//@ApiModel(value="",description="数据库表：ad_pay_refund_record")
public class AdPayRefundRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.id
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="",name="id")
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.business_id
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="商家唯一编号",name="businessId")
    private String businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.merchant_order_no
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="兜礼订单号",name="merchantOrderNo")
    private String merchantOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.out_trade_no
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="兜礼订单号",name="outTradeNo")
    private String outTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.goods_code
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="商品唯一编码",name="goodsCode")
    private String goodsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.goods_amount
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="商品实收单价",name="goodsAmount")
    private String goodsAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.goods_number
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="商品数量",name="goodsNumber")
    private String goodsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.notify_url
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="退款通知地址",name="notifyUrl")
    private String notifyUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.refund_client_ip
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="客户端真实ip",name="refundClientIp")
    private String refundClientIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.refund_ip
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="退款ip",name="refundIp")
    private String refundIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.appid
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="微信appid",name="appid")
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.mch_id
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="",name="mchId")
    private String mchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.refund_price
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="退款总价格",name="refundPrice")
    private BigDecimal refundPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.refund_amount
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="退款金额",name="refundAmount")
    private BigDecimal refundAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.refund_desc
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="退款原因",name="refundDesc")
    private String refundDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.return_code
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="返回状态码",name="returnCode")
    private String returnCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.return_msg
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="",name="returnMsg")
    private String returnMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.result_code
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="",name="resultCode")
    private String resultCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.err_code
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="",name="errCode")
    private String errCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.err_code_des
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="",name="errCodeDes")
    private String errCodeDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.transaction_id
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="微信订单号",name="transactionId")
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.out_refund_no
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="兜礼退款单号",name="outRefundNo")
    private String outRefundNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.merchant_refund_no
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="商户退款订单号",name="merchantRefundNo")
    private String merchantRefundNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.refund_id
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="微信退款单号",name="refundId")
    private String refundId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.total_fee
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="订单金额",name="totalFee")
    private BigDecimal totalFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.refund_integral
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="申请退款积分金额",name="refundIntegral")
    private BigDecimal refundIntegral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.refund_fee
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="申请退款金额",name="refundFee")
    private BigDecimal refundFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.settlement_refund_fee
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="退款金额",name="settlementRefundFee")
    private BigDecimal settlementRefundFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.integral_refund_status
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="积分结算状态 SUCCESS-积分退款成功 FAIL-积分退款失败",name="integralRefundStatus")
    private String integralRefundStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.refund_status
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="退款状态 ,SUCCESS-退款成功,CHANGE-退款异常,REFUNDCLOSE—退款关闭",name="refundStatus")
    private String refundStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.refund_recv_accout
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="退款入账账户",name="refundRecvAccout")
    private String refundRecvAccout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.refund_account
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="退款资金来源",name="refundAccount")
    private String refundAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.refund_request_source
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="退款发起来源",name="refundRequestSource")
    private String refundRequestSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.create_time
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="",name="createTime")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.update_time
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="",name="updateTime")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.refund_time
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="退款完成时间",name="refundTime")
    private String refundTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_refund_record.refund_type
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="支付类型 0积分支付 1微信支付 2 积分微信支付",name="refundType")
    private Integer refundType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ad_pay_refund_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.id
     *
     * @return the value of ad_pay_refund_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.id
     *
     * @param id the value for ad_pay_refund_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.business_id
     *
     * @return the value of ad_pay_refund_record.business_id
     *
     * @mbg.generated
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.business_id
     *
     * @param businessId the value for ad_pay_refund_record.business_id
     *
     * @mbg.generated
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.merchant_order_no
     *
     * @return the value of ad_pay_refund_record.merchant_order_no
     *
     * @mbg.generated
     */
    public String getMerchantOrderNo() {
        return merchantOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.merchant_order_no
     *
     * @param merchantOrderNo the value for ad_pay_refund_record.merchant_order_no
     *
     * @mbg.generated
     */
    public void setMerchantOrderNo(String merchantOrderNo) {
        this.merchantOrderNo = merchantOrderNo == null ? null : merchantOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.out_trade_no
     *
     * @return the value of ad_pay_refund_record.out_trade_no
     *
     * @mbg.generated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.out_trade_no
     *
     * @param outTradeNo the value for ad_pay_refund_record.out_trade_no
     *
     * @mbg.generated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.goods_code
     *
     * @return the value of ad_pay_refund_record.goods_code
     *
     * @mbg.generated
     */
    public String getGoodsCode() {
        return goodsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.goods_code
     *
     * @param goodsCode the value for ad_pay_refund_record.goods_code
     *
     * @mbg.generated
     */
    public void setGoodsCode(String goodsCode) {
        this.goodsCode = goodsCode == null ? null : goodsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.goods_amount
     *
     * @return the value of ad_pay_refund_record.goods_amount
     *
     * @mbg.generated
     */
    public String getGoodsAmount() {
        return goodsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.goods_amount
     *
     * @param goodsAmount the value for ad_pay_refund_record.goods_amount
     *
     * @mbg.generated
     */
    public void setGoodsAmount(String goodsAmount) {
        this.goodsAmount = goodsAmount == null ? null : goodsAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.goods_number
     *
     * @return the value of ad_pay_refund_record.goods_number
     *
     * @mbg.generated
     */
    public String getGoodsNumber() {
        return goodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.goods_number
     *
     * @param goodsNumber the value for ad_pay_refund_record.goods_number
     *
     * @mbg.generated
     */
    public void setGoodsNumber(String goodsNumber) {
        this.goodsNumber = goodsNumber == null ? null : goodsNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.notify_url
     *
     * @return the value of ad_pay_refund_record.notify_url
     *
     * @mbg.generated
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.notify_url
     *
     * @param notifyUrl the value for ad_pay_refund_record.notify_url
     *
     * @mbg.generated
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.refund_client_ip
     *
     * @return the value of ad_pay_refund_record.refund_client_ip
     *
     * @mbg.generated
     */
    public String getRefundClientIp() {
        return refundClientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.refund_client_ip
     *
     * @param refundClientIp the value for ad_pay_refund_record.refund_client_ip
     *
     * @mbg.generated
     */
    public void setRefundClientIp(String refundClientIp) {
        this.refundClientIp = refundClientIp == null ? null : refundClientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.refund_ip
     *
     * @return the value of ad_pay_refund_record.refund_ip
     *
     * @mbg.generated
     */
    public String getRefundIp() {
        return refundIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.refund_ip
     *
     * @param refundIp the value for ad_pay_refund_record.refund_ip
     *
     * @mbg.generated
     */
    public void setRefundIp(String refundIp) {
        this.refundIp = refundIp == null ? null : refundIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.appid
     *
     * @return the value of ad_pay_refund_record.appid
     *
     * @mbg.generated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.appid
     *
     * @param appid the value for ad_pay_refund_record.appid
     *
     * @mbg.generated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.mch_id
     *
     * @return the value of ad_pay_refund_record.mch_id
     *
     * @mbg.generated
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.mch_id
     *
     * @param mchId the value for ad_pay_refund_record.mch_id
     *
     * @mbg.generated
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.refund_price
     *
     * @return the value of ad_pay_refund_record.refund_price
     *
     * @mbg.generated
     */
    public BigDecimal getRefundPrice() {
        return refundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.refund_price
     *
     * @param refundPrice the value for ad_pay_refund_record.refund_price
     *
     * @mbg.generated
     */
    public void setRefundPrice(BigDecimal refundPrice) {
        this.refundPrice = refundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.refund_amount
     *
     * @return the value of ad_pay_refund_record.refund_amount
     *
     * @mbg.generated
     */
    public BigDecimal getRefundAmount() {
        return refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.refund_amount
     *
     * @param refundAmount the value for ad_pay_refund_record.refund_amount
     *
     * @mbg.generated
     */
    public void setRefundAmount(BigDecimal refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.refund_desc
     *
     * @return the value of ad_pay_refund_record.refund_desc
     *
     * @mbg.generated
     */
    public String getRefundDesc() {
        return refundDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.refund_desc
     *
     * @param refundDesc the value for ad_pay_refund_record.refund_desc
     *
     * @mbg.generated
     */
    public void setRefundDesc(String refundDesc) {
        this.refundDesc = refundDesc == null ? null : refundDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.return_code
     *
     * @return the value of ad_pay_refund_record.return_code
     *
     * @mbg.generated
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.return_code
     *
     * @param returnCode the value for ad_pay_refund_record.return_code
     *
     * @mbg.generated
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode == null ? null : returnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.return_msg
     *
     * @return the value of ad_pay_refund_record.return_msg
     *
     * @mbg.generated
     */
    public String getReturnMsg() {
        return returnMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.return_msg
     *
     * @param returnMsg the value for ad_pay_refund_record.return_msg
     *
     * @mbg.generated
     */
    public void setReturnMsg(String returnMsg) {
        this.returnMsg = returnMsg == null ? null : returnMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.result_code
     *
     * @return the value of ad_pay_refund_record.result_code
     *
     * @mbg.generated
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.result_code
     *
     * @param resultCode the value for ad_pay_refund_record.result_code
     *
     * @mbg.generated
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode == null ? null : resultCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.err_code
     *
     * @return the value of ad_pay_refund_record.err_code
     *
     * @mbg.generated
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.err_code
     *
     * @param errCode the value for ad_pay_refund_record.err_code
     *
     * @mbg.generated
     */
    public void setErrCode(String errCode) {
        this.errCode = errCode == null ? null : errCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.err_code_des
     *
     * @return the value of ad_pay_refund_record.err_code_des
     *
     * @mbg.generated
     */
    public String getErrCodeDes() {
        return errCodeDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.err_code_des
     *
     * @param errCodeDes the value for ad_pay_refund_record.err_code_des
     *
     * @mbg.generated
     */
    public void setErrCodeDes(String errCodeDes) {
        this.errCodeDes = errCodeDes == null ? null : errCodeDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.transaction_id
     *
     * @return the value of ad_pay_refund_record.transaction_id
     *
     * @mbg.generated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.transaction_id
     *
     * @param transactionId the value for ad_pay_refund_record.transaction_id
     *
     * @mbg.generated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.out_refund_no
     *
     * @return the value of ad_pay_refund_record.out_refund_no
     *
     * @mbg.generated
     */
    public String getOutRefundNo() {
        return outRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.out_refund_no
     *
     * @param outRefundNo the value for ad_pay_refund_record.out_refund_no
     *
     * @mbg.generated
     */
    public void setOutRefundNo(String outRefundNo) {
        this.outRefundNo = outRefundNo == null ? null : outRefundNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.merchant_refund_no
     *
     * @return the value of ad_pay_refund_record.merchant_refund_no
     *
     * @mbg.generated
     */
    public String getMerchantRefundNo() {
        return merchantRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.merchant_refund_no
     *
     * @param merchantRefundNo the value for ad_pay_refund_record.merchant_refund_no
     *
     * @mbg.generated
     */
    public void setMerchantRefundNo(String merchantRefundNo) {
        this.merchantRefundNo = merchantRefundNo == null ? null : merchantRefundNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.refund_id
     *
     * @return the value of ad_pay_refund_record.refund_id
     *
     * @mbg.generated
     */
    public String getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.refund_id
     *
     * @param refundId the value for ad_pay_refund_record.refund_id
     *
     * @mbg.generated
     */
    public void setRefundId(String refundId) {
        this.refundId = refundId == null ? null : refundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.total_fee
     *
     * @return the value of ad_pay_refund_record.total_fee
     *
     * @mbg.generated
     */
    public BigDecimal getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.total_fee
     *
     * @param totalFee the value for ad_pay_refund_record.total_fee
     *
     * @mbg.generated
     */
    public void setTotalFee(BigDecimal totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.refund_integral
     *
     * @return the value of ad_pay_refund_record.refund_integral
     *
     * @mbg.generated
     */
    public BigDecimal getRefundIntegral() {
        return refundIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.refund_integral
     *
     * @param refundIntegral the value for ad_pay_refund_record.refund_integral
     *
     * @mbg.generated
     */
    public void setRefundIntegral(BigDecimal refundIntegral) {
        this.refundIntegral = refundIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.refund_fee
     *
     * @return the value of ad_pay_refund_record.refund_fee
     *
     * @mbg.generated
     */
    public BigDecimal getRefundFee() {
        return refundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.refund_fee
     *
     * @param refundFee the value for ad_pay_refund_record.refund_fee
     *
     * @mbg.generated
     */
    public void setRefundFee(BigDecimal refundFee) {
        this.refundFee = refundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.settlement_refund_fee
     *
     * @return the value of ad_pay_refund_record.settlement_refund_fee
     *
     * @mbg.generated
     */
    public BigDecimal getSettlementRefundFee() {
        return settlementRefundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.settlement_refund_fee
     *
     * @param settlementRefundFee the value for ad_pay_refund_record.settlement_refund_fee
     *
     * @mbg.generated
     */
    public void setSettlementRefundFee(BigDecimal settlementRefundFee) {
        this.settlementRefundFee = settlementRefundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.integral_refund_status
     *
     * @return the value of ad_pay_refund_record.integral_refund_status
     *
     * @mbg.generated
     */
    public String getIntegralRefundStatus() {
        return integralRefundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.integral_refund_status
     *
     * @param integralRefundStatus the value for ad_pay_refund_record.integral_refund_status
     *
     * @mbg.generated
     */
    public void setIntegralRefundStatus(String integralRefundStatus) {
        this.integralRefundStatus = integralRefundStatus == null ? null : integralRefundStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.refund_status
     *
     * @return the value of ad_pay_refund_record.refund_status
     *
     * @mbg.generated
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.refund_status
     *
     * @param refundStatus the value for ad_pay_refund_record.refund_status
     *
     * @mbg.generated
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus == null ? null : refundStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.refund_recv_accout
     *
     * @return the value of ad_pay_refund_record.refund_recv_accout
     *
     * @mbg.generated
     */
    public String getRefundRecvAccout() {
        return refundRecvAccout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.refund_recv_accout
     *
     * @param refundRecvAccout the value for ad_pay_refund_record.refund_recv_accout
     *
     * @mbg.generated
     */
    public void setRefundRecvAccout(String refundRecvAccout) {
        this.refundRecvAccout = refundRecvAccout == null ? null : refundRecvAccout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.refund_account
     *
     * @return the value of ad_pay_refund_record.refund_account
     *
     * @mbg.generated
     */
    public String getRefundAccount() {
        return refundAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.refund_account
     *
     * @param refundAccount the value for ad_pay_refund_record.refund_account
     *
     * @mbg.generated
     */
    public void setRefundAccount(String refundAccount) {
        this.refundAccount = refundAccount == null ? null : refundAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.refund_request_source
     *
     * @return the value of ad_pay_refund_record.refund_request_source
     *
     * @mbg.generated
     */
    public String getRefundRequestSource() {
        return refundRequestSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.refund_request_source
     *
     * @param refundRequestSource the value for ad_pay_refund_record.refund_request_source
     *
     * @mbg.generated
     */
    public void setRefundRequestSource(String refundRequestSource) {
        this.refundRequestSource = refundRequestSource == null ? null : refundRequestSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.create_time
     *
     * @return the value of ad_pay_refund_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.create_time
     *
     * @param createTime the value for ad_pay_refund_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.update_time
     *
     * @return the value of ad_pay_refund_record.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.update_time
     *
     * @param updateTime the value for ad_pay_refund_record.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.refund_time
     *
     * @return the value of ad_pay_refund_record.refund_time
     *
     * @mbg.generated
     */
    public String getRefundTime() {
        return refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.refund_time
     *
     * @param refundTime the value for ad_pay_refund_record.refund_time
     *
     * @mbg.generated
     */
    public void setRefundTime(String refundTime) {
        this.refundTime = refundTime == null ? null : refundTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_refund_record.refund_type
     *
     * @return the value of ad_pay_refund_record.refund_type
     *
     * @mbg.generated
     */
    public Integer getRefundType() {
        return refundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_refund_record.refund_type
     *
     * @param refundType the value for ad_pay_refund_record.refund_type
     *
     * @mbg.generated
     */
    public void setRefundType(Integer refundType) {
        this.refundType = refundType;
    }
}