package com.doooly.entity.payment;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

//@ApiModel(value="",description="数据库表：ad_pay_record")
public class AdPayRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.id
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="",name="id")
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.pay_id
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="兜礼预支付id",name="payId")
    private String payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.business_id
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="商户编号",name="businessId")
    private String businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.mobile
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="手机号",name="mobile")
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.merchant_name
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="商户名称",name="merchantName")
    private String merchantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.merchant_order_no
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="商户订单号",name="merchantOrderNo")
    private String merchantOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.out_trade_no
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="兜礼订单号",name="outTradeNo")
    private String outTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.order_price
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="订单总价格",name="orderPrice")
    private BigDecimal orderPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.order_amount
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="订单总金额",name="orderAmount")
    private BigDecimal orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.order_body
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="订单body",name="orderBody")
    private String orderBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.pay_type
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="支付类型 0积分支付 1微信支付 2 积分微信支付",name="payType")
    private Byte payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.integral_pay_amount
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="积分支付金额",name="integralPayAmount")
    private BigDecimal integralPayAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.integral_rebate_amount
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="积分抵扣金额",name="integralRebateAmount")
    private BigDecimal integralRebateAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.integral_rebate_pay_amount
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="积分抵扣后支付金额",name="integralRebatePayAmount")
    private BigDecimal integralRebatePayAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.pay_amount
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="第三方支付金额",name="payAmount")
    private BigDecimal payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.notify_url
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="交易通知地址",name="notifyUrl")
    private String notifyUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.client_ip
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="客户端ip",name="clientIp")
    private String clientIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.order_ip
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="订单ip",name="orderIp")
    private String orderIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.integral_pay_status
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="积分支付状态 0 未支付，1支付成功, 2支付失败 , 3退款",name="integralPayStatus")
    private Byte integralPayStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.pay_status
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="支付状态 0 未支付，1支付成功,2支付失败,3退款",name="payStatus")
    private Byte payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.trade_type
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="交易类型 APP,H5",name="tradeType")
    private String tradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.order_period
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="订单有效期(单位分钟)",name="orderPeriod")
    private Short orderPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.expire_time
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="订单到期时间",name="expireTime")
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.remark
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="",name="remark")
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.integral_refund_count
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="退还积分次数",name="integralRefundCount")
    private Integer integralRefundCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.integral_refund_amount
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="积分退还总金额",name="integralRefundAmount")
    private BigDecimal integralRefundAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.refund_count
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="退款次数",name="refundCount")
    private Integer refundCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.refund_amount
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="成功退款总金额",name="refundAmount")
    private BigDecimal refundAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.return_code
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="支付返回码",name="returnCode")
    private String returnCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.return_msg
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="",name="returnMsg")
    private String returnMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.result_code
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="",name="resultCode")
    private String resultCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.err_code
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="",name="errCode")
    private String errCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.err_code_des
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="",name="errCodeDes")
    private String errCodeDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.appid
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="",name="appid")
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.mch_id
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="",name="mchId")
    private String mchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.transaction_id
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="微信支付订单号",name="transactionId")
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.create_time
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="创建时间",name="createTime")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.pay_end_time
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="支付完成时间",name="payEndTime")
    private Date payEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.update_time
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="更新时间",name="updateTime")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.big_order_number
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="大订单编号",name="bigOrderNumber")
    private String bigOrderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.dir_integral_switch
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="是否使用定向积分 默认0：不使用 1：使用",name="dirIntegralSwitch")
    private Byte dirIntegralSwitch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_pay_record.redirect_url
     *
     * @mbg.generated
     */
    //@ApiModelProperty(value="支付成功跳转链接",name="redirectUrl")
    private String redirectUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ad_pay_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.id
     *
     * @return the value of ad_pay_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.id
     *
     * @param id the value for ad_pay_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.pay_id
     *
     * @return the value of ad_pay_record.pay_id
     *
     * @mbg.generated
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.pay_id
     *
     * @param payId the value for ad_pay_record.pay_id
     *
     * @mbg.generated
     */
    public void setPayId(String payId) {
        this.payId = payId == null ? null : payId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.business_id
     *
     * @return the value of ad_pay_record.business_id
     *
     * @mbg.generated
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.business_id
     *
     * @param businessId the value for ad_pay_record.business_id
     *
     * @mbg.generated
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.mobile
     *
     * @return the value of ad_pay_record.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.mobile
     *
     * @param mobile the value for ad_pay_record.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.merchant_name
     *
     * @return the value of ad_pay_record.merchant_name
     *
     * @mbg.generated
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.merchant_name
     *
     * @param merchantName the value for ad_pay_record.merchant_name
     *
     * @mbg.generated
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.merchant_order_no
     *
     * @return the value of ad_pay_record.merchant_order_no
     *
     * @mbg.generated
     */
    public String getMerchantOrderNo() {
        return merchantOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.merchant_order_no
     *
     * @param merchantOrderNo the value for ad_pay_record.merchant_order_no
     *
     * @mbg.generated
     */
    public void setMerchantOrderNo(String merchantOrderNo) {
        this.merchantOrderNo = merchantOrderNo == null ? null : merchantOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.out_trade_no
     *
     * @return the value of ad_pay_record.out_trade_no
     *
     * @mbg.generated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.out_trade_no
     *
     * @param outTradeNo the value for ad_pay_record.out_trade_no
     *
     * @mbg.generated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.order_price
     *
     * @return the value of ad_pay_record.order_price
     *
     * @mbg.generated
     */
    public BigDecimal getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.order_price
     *
     * @param orderPrice the value for ad_pay_record.order_price
     *
     * @mbg.generated
     */
    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.order_amount
     *
     * @return the value of ad_pay_record.order_amount
     *
     * @mbg.generated
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.order_amount
     *
     * @param orderAmount the value for ad_pay_record.order_amount
     *
     * @mbg.generated
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.order_body
     *
     * @return the value of ad_pay_record.order_body
     *
     * @mbg.generated
     */
    public String getOrderBody() {
        return orderBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.order_body
     *
     * @param orderBody the value for ad_pay_record.order_body
     *
     * @mbg.generated
     */
    public void setOrderBody(String orderBody) {
        this.orderBody = orderBody == null ? null : orderBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.pay_type
     *
     * @return the value of ad_pay_record.pay_type
     *
     * @mbg.generated
     */
    public Byte getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.pay_type
     *
     * @param payType the value for ad_pay_record.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(Byte payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.integral_pay_amount
     *
     * @return the value of ad_pay_record.integral_pay_amount
     *
     * @mbg.generated
     */
    public BigDecimal getIntegralPayAmount() {
        return integralPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.integral_pay_amount
     *
     * @param integralPayAmount the value for ad_pay_record.integral_pay_amount
     *
     * @mbg.generated
     */
    public void setIntegralPayAmount(BigDecimal integralPayAmount) {
        this.integralPayAmount = integralPayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.integral_rebate_amount
     *
     * @return the value of ad_pay_record.integral_rebate_amount
     *
     * @mbg.generated
     */
    public BigDecimal getIntegralRebateAmount() {
        return integralRebateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.integral_rebate_amount
     *
     * @param integralRebateAmount the value for ad_pay_record.integral_rebate_amount
     *
     * @mbg.generated
     */
    public void setIntegralRebateAmount(BigDecimal integralRebateAmount) {
        this.integralRebateAmount = integralRebateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.integral_rebate_pay_amount
     *
     * @return the value of ad_pay_record.integral_rebate_pay_amount
     *
     * @mbg.generated
     */
    public BigDecimal getIntegralRebatePayAmount() {
        return integralRebatePayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.integral_rebate_pay_amount
     *
     * @param integralRebatePayAmount the value for ad_pay_record.integral_rebate_pay_amount
     *
     * @mbg.generated
     */
    public void setIntegralRebatePayAmount(BigDecimal integralRebatePayAmount) {
        this.integralRebatePayAmount = integralRebatePayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.pay_amount
     *
     * @return the value of ad_pay_record.pay_amount
     *
     * @mbg.generated
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.pay_amount
     *
     * @param payAmount the value for ad_pay_record.pay_amount
     *
     * @mbg.generated
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.notify_url
     *
     * @return the value of ad_pay_record.notify_url
     *
     * @mbg.generated
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.notify_url
     *
     * @param notifyUrl the value for ad_pay_record.notify_url
     *
     * @mbg.generated
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.client_ip
     *
     * @return the value of ad_pay_record.client_ip
     *
     * @mbg.generated
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.client_ip
     *
     * @param clientIp the value for ad_pay_record.client_ip
     *
     * @mbg.generated
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp == null ? null : clientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.order_ip
     *
     * @return the value of ad_pay_record.order_ip
     *
     * @mbg.generated
     */
    public String getOrderIp() {
        return orderIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.order_ip
     *
     * @param orderIp the value for ad_pay_record.order_ip
     *
     * @mbg.generated
     */
    public void setOrderIp(String orderIp) {
        this.orderIp = orderIp == null ? null : orderIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.integral_pay_status
     *
     * @return the value of ad_pay_record.integral_pay_status
     *
     * @mbg.generated
     */
    public Byte getIntegralPayStatus() {
        return integralPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.integral_pay_status
     *
     * @param integralPayStatus the value for ad_pay_record.integral_pay_status
     *
     * @mbg.generated
     */
    public void setIntegralPayStatus(Byte integralPayStatus) {
        this.integralPayStatus = integralPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.pay_status
     *
     * @return the value of ad_pay_record.pay_status
     *
     * @mbg.generated
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.pay_status
     *
     * @param payStatus the value for ad_pay_record.pay_status
     *
     * @mbg.generated
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.trade_type
     *
     * @return the value of ad_pay_record.trade_type
     *
     * @mbg.generated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.trade_type
     *
     * @param tradeType the value for ad_pay_record.trade_type
     *
     * @mbg.generated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.order_period
     *
     * @return the value of ad_pay_record.order_period
     *
     * @mbg.generated
     */
    public Short getOrderPeriod() {
        return orderPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.order_period
     *
     * @param orderPeriod the value for ad_pay_record.order_period
     *
     * @mbg.generated
     */
    public void setOrderPeriod(Short orderPeriod) {
        this.orderPeriod = orderPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.expire_time
     *
     * @return the value of ad_pay_record.expire_time
     *
     * @mbg.generated
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.expire_time
     *
     * @param expireTime the value for ad_pay_record.expire_time
     *
     * @mbg.generated
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.remark
     *
     * @return the value of ad_pay_record.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.remark
     *
     * @param remark the value for ad_pay_record.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.integral_refund_count
     *
     * @return the value of ad_pay_record.integral_refund_count
     *
     * @mbg.generated
     */
    public Integer getIntegralRefundCount() {
        return integralRefundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.integral_refund_count
     *
     * @param integralRefundCount the value for ad_pay_record.integral_refund_count
     *
     * @mbg.generated
     */
    public void setIntegralRefundCount(Integer integralRefundCount) {
        this.integralRefundCount = integralRefundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.integral_refund_amount
     *
     * @return the value of ad_pay_record.integral_refund_amount
     *
     * @mbg.generated
     */
    public BigDecimal getIntegralRefundAmount() {
        return integralRefundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.integral_refund_amount
     *
     * @param integralRefundAmount the value for ad_pay_record.integral_refund_amount
     *
     * @mbg.generated
     */
    public void setIntegralRefundAmount(BigDecimal integralRefundAmount) {
        this.integralRefundAmount = integralRefundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.refund_count
     *
     * @return the value of ad_pay_record.refund_count
     *
     * @mbg.generated
     */
    public Integer getRefundCount() {
        return refundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.refund_count
     *
     * @param refundCount the value for ad_pay_record.refund_count
     *
     * @mbg.generated
     */
    public void setRefundCount(Integer refundCount) {
        this.refundCount = refundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.refund_amount
     *
     * @return the value of ad_pay_record.refund_amount
     *
     * @mbg.generated
     */
    public BigDecimal getRefundAmount() {
        return refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.refund_amount
     *
     * @param refundAmount the value for ad_pay_record.refund_amount
     *
     * @mbg.generated
     */
    public void setRefundAmount(BigDecimal refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.return_code
     *
     * @return the value of ad_pay_record.return_code
     *
     * @mbg.generated
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.return_code
     *
     * @param returnCode the value for ad_pay_record.return_code
     *
     * @mbg.generated
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode == null ? null : returnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.return_msg
     *
     * @return the value of ad_pay_record.return_msg
     *
     * @mbg.generated
     */
    public String getReturnMsg() {
        return returnMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.return_msg
     *
     * @param returnMsg the value for ad_pay_record.return_msg
     *
     * @mbg.generated
     */
    public void setReturnMsg(String returnMsg) {
        this.returnMsg = returnMsg == null ? null : returnMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.result_code
     *
     * @return the value of ad_pay_record.result_code
     *
     * @mbg.generated
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.result_code
     *
     * @param resultCode the value for ad_pay_record.result_code
     *
     * @mbg.generated
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode == null ? null : resultCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.err_code
     *
     * @return the value of ad_pay_record.err_code
     *
     * @mbg.generated
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.err_code
     *
     * @param errCode the value for ad_pay_record.err_code
     *
     * @mbg.generated
     */
    public void setErrCode(String errCode) {
        this.errCode = errCode == null ? null : errCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.err_code_des
     *
     * @return the value of ad_pay_record.err_code_des
     *
     * @mbg.generated
     */
    public String getErrCodeDes() {
        return errCodeDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.err_code_des
     *
     * @param errCodeDes the value for ad_pay_record.err_code_des
     *
     * @mbg.generated
     */
    public void setErrCodeDes(String errCodeDes) {
        this.errCodeDes = errCodeDes == null ? null : errCodeDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.appid
     *
     * @return the value of ad_pay_record.appid
     *
     * @mbg.generated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.appid
     *
     * @param appid the value for ad_pay_record.appid
     *
     * @mbg.generated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.mch_id
     *
     * @return the value of ad_pay_record.mch_id
     *
     * @mbg.generated
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.mch_id
     *
     * @param mchId the value for ad_pay_record.mch_id
     *
     * @mbg.generated
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.transaction_id
     *
     * @return the value of ad_pay_record.transaction_id
     *
     * @mbg.generated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.transaction_id
     *
     * @param transactionId the value for ad_pay_record.transaction_id
     *
     * @mbg.generated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.create_time
     *
     * @return the value of ad_pay_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.create_time
     *
     * @param createTime the value for ad_pay_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.pay_end_time
     *
     * @return the value of ad_pay_record.pay_end_time
     *
     * @mbg.generated
     */
    public Date getPayEndTime() {
        return payEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.pay_end_time
     *
     * @param payEndTime the value for ad_pay_record.pay_end_time
     *
     * @mbg.generated
     */
    public void setPayEndTime(Date payEndTime) {
        this.payEndTime = payEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.update_time
     *
     * @return the value of ad_pay_record.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.update_time
     *
     * @param updateTime the value for ad_pay_record.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.big_order_number
     *
     * @return the value of ad_pay_record.big_order_number
     *
     * @mbg.generated
     */
    public String getBigOrderNumber() {
        return bigOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.big_order_number
     *
     * @param bigOrderNumber the value for ad_pay_record.big_order_number
     *
     * @mbg.generated
     */
    public void setBigOrderNumber(String bigOrderNumber) {
        this.bigOrderNumber = bigOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.dir_integral_switch
     *
     * @return the value of ad_pay_record.dir_integral_switch
     *
     * @mbg.generated
     */
    public Byte getDirIntegralSwitch() {
        return dirIntegralSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.dir_integral_switch
     *
     * @param dirIntegralSwitch the value for ad_pay_record.dir_integral_switch
     *
     * @mbg.generated
     */
    public void setDirIntegralSwitch(Byte dirIntegralSwitch) {
        this.dirIntegralSwitch = dirIntegralSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_pay_record.redirect_url
     *
     * @return the value of ad_pay_record.redirect_url
     *
     * @mbg.generated
     */
    public String getRedirectUrl() {
        return redirectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_pay_record.redirect_url
     *
     * @param redirectUrl the value for ad_pay_record.redirect_url
     *
     * @mbg.generated
     */
    public void setRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl == null ? null : redirectUrl.trim();
    }
}