/**
 * This code generated by CodeGenerator<ptma@163.com>
 */
package com.doooly.entity.reachad;

import java.math.BigDecimal;
import java.util.Date;

/**
 * <p>实体类</p>
 * <p>Table: ad_return_points_log - 返积分日志</p>
 *
 * @since 2018-11-19 11:16:36
 */
public class AdReturnPointsLog {

    /** id - id */
    private Long id;
    /** order_id - _order表id编号 */
    private Long orderId;
    /** ad_return_points_id - 预计积分id */
    private Long adReturnPointsId;
    /** operate_amount - 交易金额· */
    private BigDecimal operateAmount;
    /** type - 积分交易类型  1：订单     5：退货单 */
    private String type;
    /** operate_type - 交易类型  1、增加   2、减少  3、平移 */
    private String operateType;
    /** del_flag - 删除标记 */
    private String delFlag;
    /** remarks - 备注信息 */
    private String remarks;
    /** create_date - 创建时间 */
    private Date createDate;
    /** update_date - 更新时间 */
    private Date updateDate;


    public Long getId(){
        return this.id;
    }
    public void setId(Long id){
        this.id = id;
    }

    public Long getOrderId(){
        return this.orderId;
    }
    public void setOrderId(Long orderId){
        this.orderId = orderId;
    }

    public Long getAdReturnPointsId(){
        return this.adReturnPointsId;
    }
    public void setAdReturnPointsId(Long adReturnPointsId){
        this.adReturnPointsId = adReturnPointsId;
    }

    public BigDecimal getOperateAmount(){
        return this.operateAmount;
    }
    public void setOperateAmount(BigDecimal operateAmount){
        this.operateAmount = operateAmount;
    }

    public String getType(){
        return this.type;
    }
    public void setType(String type){
        this.type = type;
    }

    public String getOperateType(){
        return this.operateType;
    }
    public void setOperateType(String operateType){
        this.operateType = operateType;
    }

    public String getDelFlag(){
        return this.delFlag;
    }
    public void setDelFlag(String delFlag){
        this.delFlag = delFlag;
    }

    public String getRemarks(){
        return this.remarks;
    }
    public void setRemarks(String remarks){
        this.remarks = remarks;
    }

    public Date getCreateDate(){
        return this.createDate;
    }
    public void setCreateDate(Date createDate){
        this.createDate = createDate;
    }

    public Date getUpdateDate(){
        return this.updateDate;
    }
    public void setUpdateDate(Date updateDate){
        this.updateDate = updateDate;
    }
}